import type { DailyMealPlan, FoodHistory, GuideTopic, Recipe } from './types';

export const dailyMealPlans: DailyMealPlan[] = [
  {
    id: '1',
    meals: {
      'Café da Manhã': {
        foodName: 'Mingau de Aveia com Banana',
        texture: 'creme',
        preparation: 'Cozinhe 2 colheres de sopa de aveia em flocos finos com água até formar um mingau. Misture 1/2 banana amassada.',
      },
      'Lanche da Manhã': {
        foodName: 'Mamão Papaia',
        texture: 'amassada',
        preparation: 'Amasse 1/4 de um mamão papaia maduro com um garfo.',
      },
      'Almoço': {
        foodName: 'Creme de Mandioquinha com Frango Desfiado',
        texture: 'purê',
        preparation: 'Cozinhe 1 mandioquinha e 30g de peito de frango. Amasse a mandioquinha e desfie o frango, misturando-os.',
      },
      'Lanche da Tarde': {
        foodName: 'Pera cozida',
        texture: 'amassada',
        preparation: 'Cozinhe 1/2 pera no vapor até ficar macia e amasse com um garfo.',
      },
      'Jantar': {
        foodName: 'Sopa de Abóbora com Cenoura',
        texture: 'lisa',
        preparation: 'Cozinhe 1 fatia de abóbora com 1/2 cenoura. Bata no liquidificador até obter um creme liso.',
      },
    },
  },
  {
    id: '2',
    meals: {
      'Café da Manhã': {
        foodName: 'Purê de Maçã com Canela',
        texture: 'purê',
        preparation: 'Cozinhe 1 maçã sem casca no vapor e amasse. Polvilhe uma pitada de canela (opcional).',
      },
      'Lanche da Manhã': {
        foodName: 'Abacate',
        texture: 'amassada',
        preparation: 'Amasse 1/4 de abacate maduro com um garfo.',
      },
      'Almoço': {
        foodName: 'Caldo de Feijão com Arroz',
        texture: 'lisa',
        preparation: 'Cozinhe feijão sem sal e amasse os grãos. Misture com um pouco de arroz bem cozido.',
      },
      'Lanche da Tarde': {
        foodName: 'Tiras de Manga',
        texture: 'pedaços',
        preparation: 'Corte uma fatia de manga madura e firme em tiras grossas para o bebê segurar.',
      },
      'Jantar': {
        foodName: 'Purê de Batata Doce com Carne Moída',
        texture: 'amassada',
        preparation: 'Cozinhe 1/2 batata doce e amasse. Refogue 30g de carne moída e misture ao purê.',
      },
    },
  },
  {
    id: '3',
    meals: {
      'Café da Manhã': {
        foodName: 'Panqueca de Banana (2 ingredientes)',
        texture: 'pedaços',
        preparation: 'Amasse 1 banana madura e misture com 1 ovo. Faça pequenas panquecas em frigideira antiaderente.',
      },
      'Lanche da Manhã': {
        foodName: 'Melancia',
        texture: 'pedaços',
        preparation: 'Ofereça um pedaço grande e seguro, sem sementes, para o bebê chupar e explorar.',
      },
      'Almoço': {
        foodName: 'Peixe Desfiado com Purê de Inhame',
        texture: 'amassada',
        preparation: 'Cozinhe 1 filé pequeno de peixe branco (tilápia) no vapor e desfie, verificando espinhas. Sirva com purê de inhame.',
      },
      'Lanche da Tarde': {
        foodName: 'Iogurte Natural',
        texture: 'creme',
        preparation: 'Ofereça 2-3 colheres de iogurte natural integral sem açúcar. Introduzir laticínios conforme orientação pediátrica.',
      },
      'Jantar': {
        foodName: 'Creme de Ervilha com Hortelã',
        texture: 'creme',
        preparation: 'Cozinhe ervilhas frescas ou congeladas e bata com algumas folhas de hortelã para um sabor refrescante.',
      },
    },
  },
  {
    id: '4',
    meals: {
      'Café da Manhã': {
        foodName: 'Ovo Cozido Amassado',
        texture: 'amassada',
        preparation: 'Cozinhe 1 ovo por 10 min. Amasse bem a gema (e a clara, se já introduzida) com um garfo.',
      },
      'Lanche da Manhã': {
        foodName: 'Gomos de Laranja',
        texture: 'pedaços',
        preparation: 'Ofereça um gomo de laranja lima ou outra laranja doce, sem sementes e sem a pele branca, para o bebê chupar.',
      },
      'Almoço': {
        foodName: 'Polenta Mole com Brócolis',
        texture: 'creme',
        preparation: 'Prepare uma polenta mole com fubá e água. Sirva com "arvorezinhas" de brócolis cozidas no vapor e bem picadinhas.',
      },
      'Lanche da Tarde': {
        foodName: 'Banana Assada',
        texture: 'amassada',
        preparation: 'Asse 1 banana com casca no forno até a casca ficar preta. Retire a polpa e amasse.',
      },
      'Jantar': {
        foodName: 'Sopa de Lentilha com Legumes',
        texture: 'lisa',
        preparation: 'Cozinhe lentilha com cenoura e batata. Amasse com um garfo ou bata no liquidificador.',
      },
    },
  },
  {
    id: '5',
    meals: {
      'Café da Manhã': {
        foodName: 'Mingau de Amaranto',
        texture: 'creme',
        preparation: 'Cozinhe 2 colheres de sopa de amaranto em flocos com água ou leite vegetal. Sirva com purê de frutas.',
      },
      'Lanche da Manhã': {
        foodName: 'Pêssego em pedaços',
        texture: 'pedaços',
        preparation: 'Ofereça pedaços de pêssego maduro e macio, sem casca, em formato seguro.',
      },
      'Almoço': {
        foodName: 'Cuscuz de Milho com Frango Desfiado',
        texture: 'amassada',
        preparation: 'Prepare um cuscuz simples e sirva com frango cozido e bem desfiado por cima, regado com azeite.',
      },
      'Lanche da Tarde': {
        foodName: 'Bolinho de Chuva de Banana (Assado)',
        texture: 'pedaços',
        preparation: 'Amasse uma banana, misture com aveia e um ovo. Molde bolinhos e asse até dourar. Sem açúcar.',
      },
      'Jantar': {
        foodName: 'Sopa de Feijão Branco com Espinafre',
        texture: 'lisa',
        preparation: 'Cozinhe feijão branco e bata no liquidificador com folhas de espinafre cozidas. Tempere com um fio de azeite.',
      },
    },
  },
  {
    id: '6',
    meals: {
      'Café da Manhã': {
        foodName: 'Crepioca de Banana',
        texture: 'pedaços',
        preparation: 'Misture 1 ovo com 2 colheres de goma de tapioca e 1/2 banana amassada. Asse em frigideira antiaderente.',
      },
      'Lanche da Manhã': {
        foodName: 'Uvas sem semente (cortadas em 4)',
        texture: 'pedaços',
        preparation: 'Corte uvas Thompson ou outras sem sementes em 4 partes no sentido do comprimento para segurança.',
      },
      'Almoço': {
        foodName: 'Escondidinho de Mandioca com Carne Moída',
        texture: 'amassada',
        preparation: 'Faça um purê de mandioca e cubra uma camada de carne moída refogada. Sirva a porção do bebê separada.',
      },
      'Lanche da Tarde': {
        foodName: 'Kiwi Amassado',
        texture: 'amassada',
        preparation: 'Amasse um kiwi maduro com um garfo. A acidez é ótima para o paladar em desenvolvimento.',
      },
      'Jantar': {
        foodName: 'Creme de Beterraba com Batata',
        texture: 'creme',
        preparation: 'Cozinhe beterraba e batata. Bata no liquidificador até obter um creme rosa vibrante.',
      },
    },
  },
  {
    id: '7',
    meals: {
      'Café da Manhã': {
        foodName: 'Smoothie de Morango e Iogurte',
        texture: 'líquida',
        preparation: 'Bata 3 morangos com 2 colheres de iogurte natural. Sirva em copo de treinamento.',
      },
      'Lanche da Manhã': {
        foodName: 'Palitos de Cenoura Cozida',
        texture: 'pedaços',
        preparation: 'Cozinhe cenouras no vapor até ficarem macias e corte em formato de palito para o bebê segurar.',
      },
      'Almoço': {
        foodName: 'Risoto Primavera (Arroz com Legumes Picados)',
        texture: 'amassada',
        preparation: 'Cozinhe arroz com caldo de legumes caseiro e adicione ervilhas, milho e cenoura picadinha. Deixe bem "molhadinho".',
      },
      'Lanche da Tarde': {
        foodName: 'Purê de Ameixa',
        texture: 'purê',
        preparation: 'Cozinhe 2 ameixas secas em pouca água até amolecerem bem e amasse.',
      },
      'Jantar': {
        foodName: 'Sopa de Abobrinha com Manjericão',
        texture: 'lisa',
        preparation: 'Refogue abobrinha com cebola, cozinhe e bata com folhas de manjericão fresco. Um jantar leve e digestivo.',
      },
    },
  },
];


export const recipes: Recipe[] = [
  // Café da Manhã
  {
    id: '1',
    name: 'Mingau de Aveia com Banana',
    description: 'Um clássico nutritivo e cremoso, perfeito para fornecer energia e doçura natural para começar bem o dia do bebê.',
    image: '6',
    ingredients: ['2 colheres de sopa de aveia em flocos finos', '150ml de água ou leite (materno, fórmula ou vegetal)', '1/2 banana nanica bem madura', '1 pitada de canela em pó (opcional)'],
    instructions: [
      'Em uma panela pequena, misture a aveia com a água ou leite.',
      'Leve ao fogo baixo, mexendo constantemente para não empelotar. Cozinhe por cerca de 3 a 5 minutos, ou até o mingau engrossar e a aveia estar bem cozida.',
      'Enquanto o mingau cozinha, amasse bem a banana com um garfo até formar um purê.',
      'Retire o mingau do fogo, misture o purê de banana e a canela (se for usar).',
      'Deixe amornar a uma temperatura segura para o bebê e sirva.',
    ],
    mealType: 'Café da Manhã',
    ageGroup: '6-8 meses',
    texture: 'Creme',
    cookingTime: '5-7 min',
    cookingInfo: 'Fogo baixo, panela pequena.',
  },
  {
    id: '11',
    name: 'Panquequinha de Banana e Aveia',
    description: 'Uma panqueca fofinha, sem açúcar e fácil para as mãozinhas do bebê segurarem. Ótima para o método BLW.',
    image: '11',
    ingredients: ['1 banana prata madura', '1 ovo', '2 colheres de sopa de farinha de aveia', 'Óleo de coco ou azeite para untar'],
    instructions: [
      'Em uma tigela, amasse bem a banana até virar um purê homogêneo.',
      'Adicione o ovo e bata bem com um garfo ou fouet até incorporar.',
      'Acrescente a farinha de aveia e misture até formar uma massa uniforme.',
      'Aqueça uma frigideira antiaderente em fogo baixo e unte com um pouco de óleo de coco ou azeite.',
      'Com uma colher, despeje pequenas porções da massa para formar as panquequinhas.',
      'Cozinhe por cerca de 2 minutos de cada lado, ou até ficarem douradas e firmes.',
      'Deixe esfriar e sirva em tiras ou inteira, dependendo da habilidade do bebê.',
    ],
    mealType: 'Café da Manhã',
    ageGroup: '9-11 meses',
    texture: 'Pedaços macios',
    cookingTime: '10 min',
    cookingInfo: 'Fogo baixo, frigideira antiaderente.',
  },
  {
    id: '12',
    name: 'Ovos Mexidos Cremosos',
    description: 'Fonte de proteína e gorduras boas para um café da manhã reforçado e cheio de sabor. A textura é ideal para bebês que já exploram alimentos mais consistentes.',
    image: '8',
    ingredients: ['1 ovo', '1 colher de sopa de leite (materno, fórmula ou integral) ou água', '1 fio de azeite de oliva'],
    instructions: [
      'Quebre o ovo em uma tigela pequena e adicione o leite ou água. Bata bem com um garfo.',
      'Aqueça uma frigideira antiaderente em fogo baixo e adicione o azeite.',
      'Despeje a mistura de ovo na frigideira.',
      'Com uma espátula, mexa suavemente e continuamente, raspando o fundo, para que os ovos cozinhem de forma uniforme e fiquem cremosos.',
      'Cozinhe até atingir a consistência desejada, mas sem deixar ressecar. Sirva morno.',
    ],
    mealType: 'Café da Manhã',
    ageGroup: '9-11 meses',
    texture: 'Amassado',
    cookingTime: '5 min',
    cookingInfo: 'Fogo baixo, frigideira antiaderente.',
  },
  {
    id: '13',
    name: 'Vitamina de Abacate e Maçã',
    description: 'Refrescante, nutritiva e cheia de gorduras saudáveis do abacate. A maçã adiciona um doce natural e fibras.',
    image: '13',
    ingredients: ['1/4 de abacate maduro', '1/2 maçã pequena, sem casca e sem sementes', '50ml de água ou leite'],
    instructions: [
      'Pique a maçã em pedaços pequenos.',
      'Coloque o abacate, a maçã picada e a água ou leite no liquidificador.',
      'Bata em alta velocidade até obter uma mistura completamente homogênea e cremosa.',
      'Se ficar muito espesso, adicione um pouco mais de líquido.',
      'Sirva imediatamente em um copo de treinamento.',
    ],
    mealType: 'Café da Manhã',
    ageGroup: '12+ meses',
    texture: 'Creme',
    cookingTime: '3 min',
    cookingInfo: 'Liquidificador.',
  },
  {
    id: '14',
    name: 'Torrada com Pasta de Amendoim',
    description: 'Uma opção cheia de energia e proteína para os pequenos aventureiros. Certifique-se de usar pasta de amendoim integral e sem açúcar.',
    image: '14',
    ingredients: ['1 fatia de pão de forma integral', '1 colher de chá de pasta de amendoim 100% integral'],
    instructions: [
      'Toste levemente a fatia de pão na torradeira ou em uma frigideira.',
      'Espalhe uma camada BEM FINA de pasta de amendoim sobre a torrada. Uma camada grossa pode apresentar risco de engasgo.',
      'Corte a torrada em tiras ou pedaços pequenos, adequados para a idade do bebê.',
      'Monitore o bebê durante a alimentação. O amendoim é um potencial alérgeno.',
    ],
    mealType: 'Café da Manhã',
    ageGroup: '12+ meses',
    texture: 'Pedaços macios',
    cookingTime: '3 min',
    cookingInfo: 'Torradeira ou frigideira.',
  },

  // Almoço
  {
    id: '2',
    name: 'Purê de Mandioquinha Cremoso',
    description: 'Um purê suave, adocicado e de fácil digestão, sendo um dos favoritos na introdução alimentar. A mandioquinha é rica em carboidratos que fornecem energia.',
    image: '2',
    ingredients: ['1 mandioquinha (batata-baroa) média', '1 fio de azeite de oliva extra virgem', 'Água do cozimento (se necessário)'],
    instructions: [
      'Lave, descasque e corte a mandioquinha em rodelas.',
      'Cozinhe no vapor ou em pouca água até ficar muito macia (um garfo deve entrar e sair com facilidade).',
      'Retire do fogo e amasse bem com um garfo até formar um purê liso.',
      'Adicione um fio de azeite e, se necessário, um pouco da água do cozimento para atingir a consistência desejada.',
      'Deixe amornar e sirva.',
    ],
    mealType: 'Almoço',
    ageGroup: '6-8 meses',
    texture: 'Purê',
    cookingTime: '15 min',
    cookingInfo: 'Fogo médio, panela com água ou vaporizador.',
  },
  {
    id: '3',
    name: 'Frango Desfiado com Cenoura',
    description: 'Uma combinação clássica para introduzir proteína e vitamina A. A cenoura adocicada complementa o sabor suave do frango.',
    image: '3',
    ingredients: ['30g de peito de frango sem osso e sem pele', '1/2 cenoura pequena', 'Folhas de salsinha ou coentro (opcional)'],
    instructions: [
      'Cozinhe o frango em água (sem sal) até ficar bem cozido e macio.',
      'Em outra panela, cozinhe a cenoura no vapor ou em água até ficar bem macia.',
      'Desfie o frango finamente com dois garfos ou usando um processador.',
      'Amasse a cenoura com um garfo.',
      'Misture o frango desfiado com a cenoura amassada e as ervas picadinhas (se usar).',
      'Pode adicionar um pouco da água do cozimento do frango para umedecer e dar mais sabor.',
    ],
    mealType: 'Almoço',
    ageGroup: '9-11 meses',
    texture: 'Amassado',
    cookingTime: '20 min',
    cookingInfo: 'Fogo médio, duas panelas pequenas.',
  },
  {
    id: '7',
    name: 'Caldo de Feijão Encorpado',
    description: 'Uma forma inicial e segura de introduzir o feijão, uma excelente fonte de ferro. O caldo concentrado é fácil de digerir e muito nutritivo.',
    image: '7',
    ingredients: ['1/2 xícara de feijão cozido (sem sal e temperos)', '1/4 xícara da própria água do cozimento do feijão'],
    instructions: [
      'Certifique-se de que o feijão foi cozido apenas em água.',
      'Coloque o feijão cozido e a água do cozimento no liquidificador.',
      'Bata em alta velocidade por cerca de 1 minuto.',
      'Passe a mistura por uma peneira fina, pressionando com uma colher para extrair apenas o caldo e a polpa, descartando as cascas.',
      'O resultado é um caldo cremoso e rico. Ofereça puro com uma colher ou misturado em outros purês (como de batata ou abóbora).',
    ],
    mealType: 'Almoço',
    ageGroup: '6-8 meses',
    texture: 'Sopa',
    cookingTime: '5 min (com feijão já cozido)',
    cookingInfo: 'Liquidificador e peneira.',
  },
  {
    id: '8',
    name: 'Ovinho Amassado com Azeite',
    description: 'O ovo é um superalimento! Rico em proteína de alta qualidade, colina e vitaminas. Uma ótima opção para variar o cardápio.',
    image: '8',
    ingredients: ['1 ovo', '1 colher de chá de azeite de oliva extra virgem'],
    instructions: [
      'Coloque o ovo em uma panela pequena e cubra com água.',
      'Leve ao fogo alto e, quando a água ferver, conte 10 minutos (ovo bem cozido).',
      'Retire o ovo da água quente e coloque-o em um recipiente com água fria para facilitar na hora de descascar.',
      'Descasque e amasse bem a gema e a clara com um garfo.',
      'Regue com o azeite, misture e sirva morno.',
      'O ovo é um potencial alérgeno, introduza com atenção.',
    ],
    mealType: 'Almoço',
    ageGroup: '6-8 meses',
    texture: 'Amassado',
    cookingTime: '12 min',
    cookingInfo: 'Fogo alto, panela pequena com água.',
  },
  {
    id: '9',
    name: 'Purê de Abóbora com Toque de Sálvia',
    description: 'A abóbora cabotiá tem um sabor adocicado natural que os bebês amam. A sálvia adiciona uma camada de aroma sofisticada e suave.',
    image: '9',
    ingredients: ['1 fatia média de abóbora cabotiá', '1 folha de sálvia fresca (opcional)', '1 fio de azeite'],
    instructions: [
      'Descasque a abóbora e corte em cubos.',
      'Cozinhe a abóbora no vapor junto com a folha de sálvia (se for usar) até ficar extremamente macia.',
      'Retire a folha de sálvia e descarte-a.',
      'Amasse a abóbora com um garfo até obter a consistência de purê.',
      'Adicione o azeite, misture bem e sirva morno.',
    ],
    mealType: 'Almoço',
    ageGroup: '6-8 meses',
    texture: 'Purê',
    cookingTime: '20 min',
    cookingInfo: 'Fogo médio, panela a vapor.',
  },
  {
    id: '15',
    name: 'Risoto Falso de Legumes para Bebês',
    description: 'Um prato "de gente grande" adaptado para os pequenos. O arroz bem cozido e cremoso é uma ótima forma de oferecer grãos e legumes juntos.',
    image: '15',
    ingredients: ['2 colheres de sopa de arroz arbóreo ou comum', 'Legumes variados bem picados (1 colher de sopa de cada): abobrinha, cenoura, ervilha', '300ml de caldo de legumes caseiro (sem sal) ou água', '1 fio de azeite'],
    instructions: [
      'Em uma panela pequena, aqueça o azeite e refogue o arroz por um minuto.',
      'Adicione os legumes picados e refogue por mais um minuto.',
      'Acrescente metade do caldo de legumes quente, mexa e deixe cozinhar em fogo baixo.',
      'Continue mexendo ocasionalmente e adicionando mais caldo à medida que for secando, até o arroz ficar bem macio e o risoto cremoso.',
      'Deixe amornar e sirva. Não precisa adicionar queijo.',
    ],
    mealType: 'Almoço',
    ageGroup: '12+ meses',
    texture: 'Pedaços macios',
    cookingTime: '25 min',
    cookingInfo: 'Fogo baixo, panela pequena.',
  },
  {
    id: '16',
    name: 'Peixinho no Vapor com Batata',
    description: 'Uma introdução suave ao peixe, rico em Ômega 3. A batata complementa com carboidratos para dar energia.',
    image: '16',
    ingredients: ['30g de filé de peixe branco sem espinhas (tilápia, pescada)', '1 batata pequena', 'Gotas de limão e salsinha picada (opcional)'],
    instructions: [
      'Tempere o peixe com algumas gotas de limão.',
      'Descasque a batata e corte em rodelas.',
      'Cozinhe o peixe e a batata no vapor até ficarem bem macios (cerca de 15 minutos).',
      'Verifique CUIDADOSAMENTE se não há nenhuma espinha no peixe e desfie-o.',
      'Amasse a batata com um garfo.',
      'Misture o peixe desfiado, a batata amassada e a salsinha (se usar). Sirva morno.',
    ],
    mealType: 'Almoço',
    ageGroup: '9-11 meses',
    texture: 'Amassado',
    cookingTime: '15 min',
    cookingInfo: 'Fogo médio, panela a vapor.',
  },
  {
    id: '17',
    name: 'Carne de Panela Desfiada (Super Macia)',
    description: 'Uma introdução saborosa e rica em ferro à carne vermelha. O cozimento lento na pressão garante uma textura que desmancha na boca.',
    image: '17',
    ingredients: ['50g de músculo ou acém em cubos', '1/2 tomate pequeno, sem pele e sem sementes', '1/4 de cebola pequena', '1 folha de louro (opcional)'],
    instructions: [
      'Em uma panela de pressão, coloque a carne, o tomate, a cebola e a folha de louro. Adicione um pouco de água (cerca de 1/2 xícara).',
      'Cozinhe na pressão por cerca de 30-40 minutos após pegar pressão, ou até a carne ficar extremamente macia.',
      'Retire a folha de louro. Desfie a carne com um garfo.',
      'Sirva a carne desfiada com o caldinho que se formou na panela. Pode acompanhar um purê de mandioquinha ou batata.',
    ],
    mealType: 'Almoço',
    ageGroup: '9-11 meses',
    texture: 'Pedaços macios',
    cookingTime: '40 min',
    cookingInfo: 'Fogo médio, panela de pressão.',
  },
  {
    id: '18',
    name: 'Sopa de Lentilha com Legumes',
    description: 'Rica em ferro e fibras, esta sopa é reconfortante e muito nutritiva. Perfeita para fortalecer a imunidade do bebê.',
    image: '18',
    ingredients: ['3 colheres de sopa de lentilha (deixar de molho por 2h)', '1/2 cenoura em cubos pequenos', '1/2 batata em cubos pequenos', '1 fio de azeite'],
    instructions: [
      'Descarte a água do molho da lentilha.',
      'Em uma panela, cozinhe a lentilha com a cenoura e a batata em água limpa até todos os ingredientes ficarem bem macios.',
      'Para uma textura mais lisa (6-8 meses), bata no liquidificador.',
      'Para uma textura com pedacinhos (9+ meses), amasse com um garfo.',
      'Regue com um fio de azeite antes de servir.',
    ],
    mealType: 'Almoço',
    ageGroup: '6-8 meses',
    texture: 'Sopa',
    cookingTime: '30 min',
    cookingInfo: 'Fogo médio, panela de pressão ou comum.',
  },
  {
    id: '19',
    name: 'Macarrãozinho com Molho de Brócolis',
    description: 'Uma forma divertida de comer vegetais verdes! O brócolis se transforma em um "molho" que adere bem ao macarrão.',
    image: '19',
    ingredients: ['30g de macarrão para bebês (letrinhas, estrelinhas)', 'Floretes de 1/2 xícara de brócolis', '1 dente de alho pequeno (opcional)', 'Azeite de oliva'],
    instructions: [
      'Cozinhe o macarrão em água fervente conforme as instruções da embalagem, mas deixe passar um pouco do ponto para ficar mais macio.',
      'Enquanto isso, cozinhe os floretes de brócolis no vapor até ficarem bem macios.',
      'Em uma frigideira, aqueça um fio de azeite e doure levemente o alho amassado (se usar). Adicione o brócolis cozido e amasse com um garfo, formando um "molho" rústico.',
      'Escorra o macarrão e misture ao molho de brócolis. Sirva morno.',
    ],
    mealType: 'Almoço',
    ageGroup: '12+ meses',
    texture: 'Pedaços macios',
    cookingTime: '15 min',
    cookingInfo: 'Fogo médio, panela com água e frigideira.',
  },

  // Jantar
  {
    id: '5',
    name: 'Purê de Batata Doce com Espinafre',
    description: 'Uma combinação poderosa e colorida, rica em ferro (espinafre) e Vitamina A (batata doce). Um jantar leve e nutritivo.',
    image: '5',
    ingredients: ['1/2 batata doce laranja pequena', 'Um punhado de folhas de espinafre fresco', '1 fio de azeite'],
    instructions: [
      'Asse ou cozinhe a batata doce no vapor até ficar macia.',
      'Lave bem as folhas de espinafre. Em uma panela, coloque o espinafre com a própria água que escorre da lavagem e abafe por 1-2 minutos, até murchar.',
      'Pique o espinafre murcho bem fininho.',
      'Amasse a batata doce com um garfo e misture com o espinafre picado e um fio de azeite.',
      'Sirva morno.',
    ],
    mealType: 'Jantar',
    ageGroup: '6-8 meses',
    texture: 'Purê',
    cookingTime: '25 min',
    cookingInfo: 'Forno ou panela a vapor.',
  },
  {
    id: '20',
    name: 'Canja de Galinha para Bebê',
    description: 'Um clássico que aquece o coração e a alma. Leve, reconfortante e nutritiva, ideal para uma noite tranquila.',
    image: '20',
    ingredients: ['30g de frango em cubos pequenos', '2 colheres de sopa de arroz', '1/2 cenoura pequena picada', 'Salsinha picada'],
    instructions: [
      'Em uma panela, cozinhe o frango com a cenoura em caldo de legumes caseiro (ou água) até o frango ficar macio.',
      'Adicione o arroz e cozinhe em fogo baixo até o arroz e os legumes estarem bem macios e a canja cremosa.',
      'Verifique se o frango precisa ser mais desfiado. Amasse os pedaços maiores de cenoura com uma colher.',
      'Finalize com a salsinha picada antes de servir.',
    ],
    mealType: 'Jantar',
    ageGroup: '9-11 meses',
    texture: 'Sopa',
    cookingTime: '30 min',
    cookingInfo: 'Fogo médio, panela média.',
  },
  {
    id: '21',
    name: 'Creme de Abobrinha e Manjericão',
    description: 'Leve, de fácil digestão e com um aroma delicioso, este creme é perfeito para o jantar. O manjericão dá um toque especial.',
    image: '21',
    ingredients: ['1 abobrinha pequena', '1/4 de cebola', '2-3 folhas de manjericão fresco', '1 fio de azeite'],
    instructions: [
      'Em uma panela, aqueça o azeite e refogue a cebola picada até ficar transparente.',
      'Adicione a abobrinha em rodelas e cubra com água.',
      'Cozinhe em fogo médio até a abobrinha ficar muito macia (cerca de 10 minutos).',
      'Despeje tudo no liquidificador, adicione as folhas de manjericão e bata até obter um creme liso.',
      'Sirva morno.',
    ],
    mealType: 'Jantar',
    ageGroup: '6-8 meses',
    texture: 'Creme',
    cookingTime: '15 min',
    cookingInfo: 'Fogo baixo, panela pequena e liquidificador.',
  },
  {
    id: '22',
    name: 'Polenta Mole com Ragú de Carne',
    description: 'Um prato substancioso e cheio de sabor, que conforta e satisfaz. A polenta cremosa é uma base perfeita para a carne moída.',
    image: '22',
    ingredients: ['2 colheres de sopa de fubá mimoso', '30g de carne moída (patinho)', '1/4 xícara de molho de tomate caseiro (sem sal)', 'Azeite, cebola e alho para refogar'],
    instructions: [
      'Prepare a polenta: dissolva o fubá em 1 xícara de água ou caldo de legumes. Leve ao fogo baixo, mexendo sempre, até cozinhar e engrossar.',
      'Prepare o ragú: refogue a cebola e o alho no azeite, adicione a carne moída e cozinhe até dourar. Junte o molho de tomate e deixe apurar.',
      'Sirva a polenta cremosa em uma tigela com o ragú de carne por cima.',
    ],
    mealType: 'Jantar',
    ageGroup: '12+ meses',
    texture: 'Creme',
    cookingTime: '20 min',
    cookingInfo: 'Fogo baixo/médio, duas panelas pequenas.',
  },
  {
    id: '23',
    name: 'Mini Omelete de Forno com Queijo',
    description: 'Prático, versátil e perfeito para o jantar. O formato de muffin facilita para o bebê comer com as mãos.',
    image: '23',
    ingredients: ['1 ovo', '1 colher de sopa de queijo cottage ou ricota amassada', 'Salsinha ou cebolinha picada', 'Opcional: 1 colher de espinafre picado'],
    instructions: [
      'Pré-aqueça o forno a 180°C. Unte forminhas de mini muffin.',
      'Em uma tigela, bata bem o ovo.',
      'Misture o queijo, as ervas e o espinafre (se usar).',
      'Despeje a mistura nas forminhas, preenchendo cerca de 3/4 da capacidade.',
      'Asse por 15-20 minutos, ou até que os omeletes estejam firmes e levemente dourados.',
      'Deixe esfriar um pouco antes de desenformar e servir.',
    ],
    mealType: 'Jantar',
    ageGroup: '12+ meses',
    texture: 'Pedaços macios',
    cookingTime: '20 min',
    cookingInfo: 'Forno a 180°C, forminhas de muffin.',
  },
  {
    id: '24',
    name: 'Sopa de Abóbora com Gengibre',
    description: 'Uma sopa adocicada com um toque de gengibre que aquece e ajuda na digestão. A cor vibrante também encanta os pequenos.',
    image: '9',
    ingredients: ['1 xícara de abóbora em cubos', '1 rodela bem fina de gengibre fresco (opcional)', '1 fio de azeite'],
    instructions: [
      'Cozinhe a abóbora com a rodela de gengibre no vapor ou em pouca água até ficar muito macia.',
      'Retire o gengibre e descarte-o.',
      'Bata a abóbora no liquidificador, adicionando um pouco da água do cozimento se necessário para atingir a consistência de sopa.',
      'Sirva morna com um fio de azeite.',
    ],
    mealType: 'Jantar',
    ageGroup: '6-8 meses',
    texture: 'Sopa',
    cookingTime: '20 min',
    cookingInfo: 'Fogo médio, panela a vapor ou comum.',
  },
  {
    id: '25',
    name: 'Rolinhos de Frango com Espinafre',
    description: 'Uma maneira criativa e elegante de apresentar a proteína no jantar, com um recheio nutritivo e saboroso.',
    image: '25',
    ingredients: ['1 filé de frango fino (cerca de 50g)', 'Folhas de espinafre cozidas e picadas', '1 colher de sopa de ricota amassada'],
    instructions: [
      'Abra o filé de frango em uma tábua. Se necessário, bata um pouco para afiná-lo.',
      'Misture a ricota com o espinafre picado e espalhe sobre o filé.',
      'Enrole o filé como um rocambole e prenda com um palito de dente.',
      'Cozinhe no vapor ou asse em forno pré-aquecido a 180°C por cerca de 20-25 minutos.',
      'Retire o palito, deixe amornar e fatie em rodelas antes de servir.',
    ],
    mealType: 'Jantar',
    ageGroup: '12+ meses',
    texture: 'Pedaços macios',
    cookingTime: '25 min',
    cookingInfo: 'Forno a 180°C ou panela a vapor.',
  },
  {
    id: '26',
    name: 'Purê de Inhame com Couve Refogada',
    description: 'Inhame é uma ótima fonte de energia e vitaminas. A couve adiciona ferro e um saborzinho especial ao purê.',
    image: '26',
    ingredients: ['1 inhame pequeno', '2 folhas de couve picadas bem fininhas (sem o talo)', '1/2 dente de alho pequeno amassado (opcional)', 'Azeite'],
    instructions: [
      'Descasque o inhame, corte em pedaços e cozinhe no vapor até ficar muito macio.',
      'Amasse o inhame com um garfo até formar um purê.',
      'Em uma frigideira, aqueça um fio de azeite e refogue rapidamente o alho (se usar). Adicione a couve e refogue até murchar.',
      'Misture a couve refogada ao purê de inhame e sirva.',
    ],
    mealType: 'Jantar',
    ageGroup: '9-11 meses',
    texture: 'Amassado',
    cookingTime: '20 min',
    cookingInfo: 'Fogo médio, panela a vapor e frigideira.',
  },
  {
    id: '27',
    name: 'Quibebe de Abóbora',
    description: 'Um clássico da culinária brasileira em uma versão suave para bebês. É um creme rústico, nutritivo e muito saboroso.',
    image: '27',
    ingredients: ['1 xícara de abóbora em cubos', '1/4 de cebola picada', 'Salsinha picada', 'Azeite'],
    instructions: [
      'Em uma panela, aqueça um fio de azeite e refogue a cebola até ficar transparente.',
      'Adicione a abóbora, uma pitada de salsinha e cubra com um pouco de água (só o suficiente para cozinhar).',
      'Cozinhe em fogo baixo, com a panela semi-tampada, até a abóbora ficar tão macia que começa a desmanchar.',
      'Amasse os pedaços restantes com a própria colher, formando um creme rústico (o quibebe).',
      'Sirva morno.',
    ],
    mealType: 'Jantar',
    ageGroup: '9-11 meses',
    texture: 'Creme',
    cookingTime: '25 min',
    cookingInfo: 'Fogo baixo, panela média.',
  },
  {
    id: '28',
    name: 'Bolinho de Arroz com Legumes (Assado)',
    description: 'Uma ótima forma de reaproveitar o arroz do almoço e evitar o desperdício, criando um jantar divertido e fácil de comer com as mãos.',
    image: '28',
    ingredients: ['1/2 xícara de arroz cozido', '1 ovo pequeno', '2 colheres de sopa de legumes cozidos e picados (cenoura, ervilha, brócolis)', '1 colher de sopa de queijo parmesão ralado (opcional)'],
    instructions: [
      'Pré-aqueça o forno a 180°C e unte uma assadeira ou use tapete de silicone.',
      'Em uma tigela, misture bem o arroz cozido, o ovo, os legumes e o queijo (se usar) até formar uma massinha.',
      'Com as mãos úmidas, molde pequenos bolinhos ou discos.',
      'Disponha os bolinhos na assadeira e asse por cerca de 15-20 minutos, ou até ficarem firmes e levemente dourados.',
      'Deixe amornar antes de servir.',
    ],
    mealType: 'Jantar',
    ageGroup: '12+ meses',
    texture: 'Pedaços macios',
    cookingTime: '20 min',
    cookingInfo: 'Forno a 180°C, assadeira.',
  },

  // Sobremesas
  {
    id: '4',
    name: 'Papinha de Pera com Gengibre',
    description: 'A doçura da pera com um toque levemente picante e aromático do gengibre. Ótimo para explorar novos sabores e ajudar na digestão.',
    image: '4',
    ingredients: ['1 pera madura e suculenta (tipo Williams)', '1 rodela bem fina de gengibre fresco'],
    instructions: [
      'Descasque a pera, retire o miolo e pique em pedaços.',
      'Coloque a pera e a rodela de gengibre em uma panela pequena com um pouquinho de água (só para não queimar).',
      'Cozinhe em fogo baixo por cerca de 10 minutos, até a pera ficar bem macia.',
      'Retire e descarte a rodela de gengibre.',
      'Amasse a pera com um garfo até atingir a consistência desejada.',
      'Sirva morno ou frio.',
    ],
    mealType: 'Sobremesa',
    ageGroup: '6-8 meses',
    texture: 'Amassado',
    cookingTime: '10 min',
    cookingInfo: 'Fogo baixo, panela pequena.',
  },
  {
    id: '10',
    name: 'Tiras de Manga Seguras (BLW)',
    description: 'Uma fruta doce e suculenta para o bebê explorar com as próprias mãos. Excelente para o desenvolvimento da coordenação motora.',
    image: '10',
    ingredients: ['1 fatia grossa de manga madura, mas ainda firme (tipo Palmer ou Tommy)'],
    instructions: [
      'Descasque a manga.',
      'Corte a polpa em tiras grossas, com um tamanho que o bebê consiga segurar com a mão fechada, deixando uma parte para fora.',
      'Certifique-se de que a manga não está escorregadia demais. Se estiver, pode "empanar" em farinha de aveia para melhorar a pega.',
      'Ofereça para o bebê explorar. Supervisione sempre.',
    ],
    mealType: 'Sobremesa',
    ageGroup: '9-11 meses',
    texture: 'Pedaços macios',
    cookingTime: '2 min',
    cookingInfo: 'Sem cozimento.',
  },
  {
    id: '29',
    name: 'Purê Clássico de Maçã e Canela',
    description: 'Um clássico da introdução alimentar. É suave, adocicado, fácil de digerir e o cheirinho de canela é irresistível.',
    image: '1',
    ingredients: ['1 maçã (tipo Gala ou Fuji)', 'Uma pitada de canela em pó', '2 colheres de sopa de água'],
    instructions: [
      'Lave, descasque, retire as sementes e pique a maçã.',
      'Em uma panela pequena, coloque a maçã picada e a água. Cozinhe em fogo baixo, com a panela tampada, por cerca de 8-10 minutos, até a maçã ficar bem macia.',
      'Amasse com um garfo ou, para um purê mais liso, bata no liquidificador.',
      'Polvilhe a canela (se desejar), misture e sirva morno ou em temperatura ambiente.',
    ],
    mealType: 'Sobremesa',
    ageGroup: '6-8 meses',
    texture: 'Purê',
    cookingTime: '10 min',
    cookingInfo: 'Fogo baixo, panela pequena.',
  },
  {
    id: '30',
    name: 'Banana Assada com Canela',
    description: 'Uma sobremesa quentinha, doce e reconfortante. Assar a banana intensifica seu sabor e a deixa com uma textura de purê natural.',
    image: '30',
    ingredients: ['1 banana prata ou nanica', 'Canela em pó a gosto'],
    instructions: [
      'Pré-aqueça o forno a 180°C.',
      'Coloque a banana com a casca diretamente na assadeira.',
      'Asse por cerca de 15 minutos, ou até a casca ficar completamente preta.',
      'Retire do forno com cuidado. Faça um corte na casca e, com uma colher, retire a polpa, que estará muito macia.',
      'Amasse a polpa, polvilhe canela e sirva morna.',
    ],
    mealType: 'Sobremesa',
    ageGroup: '9-11 meses',
    texture: 'Amassado',
    cookingTime: '15 min',
    cookingInfo: 'Forno a 180°C.',
  },
  {
    id: '31',
    name: 'Picolé 100% Melancia',
    description: 'Refrescante, hidrante e sem nenhum açúcar adicionado. Perfeito para dias quentes e para aliviar o desconforto dos dentinhos nascendo.',
    image: '31',
    ingredients: ['2 fatias de melancia sem sementes'],
    instructions: [
      'Corte a melancia em pedaços e retire todas as sementes.',
      'Bata a melancia no liquidificador até virar um suco.',
      'Despeje o suco em forminhas de picolé apropriadas para bebês.',
      'Leve ao congelador por pelo menos 4 horas, ou até firmar completamente.',
      'Para desenformar, passe a forminha rapidamente em água corrente.',
    ],
    mealType: 'Sobremesa',
    ageGroup: '12+ meses',
    texture: 'Pedaços macios',
    cookingTime: '4 horas (congelamento)',
    cookingInfo: 'Liquidificador e congelador.',
  },
  {
    id: '32',
    name: 'Creme Tropical de Manga e Maracujá',
    description: 'Uma combinação vibrante e deliciosa, com a doçura da manga e a acidez suave do maracujá. Uma explosão de sabor para o paladar do bebê.',
    image: '32',
    ingredients: ['1/2 manga Palmer madura', 'Polpa de 1/4 de maracujá doce (passe na peneira para remover as sementes)'],
    instructions: [
      'Descasque e pique a manga.',
      'No liquidificador ou mixer, bata a manga com a polpa de maracujá peneirada.',
      'Bata até obter um creme liso e aerado.',
      'Sirva geladinho.',
    ],
    mealType: 'Sobremesa',
    ageGroup: '12+ meses',
    texture: 'Creme',
    cookingTime: '5 min',
    cookingInfo: 'Liquidificador ou mixer.',
  },
  {
    id: '33',
    name: 'Compota de Maçã e Ameixa',
    description: 'Uma sobremesa clássica e funcional, que ajuda a regular o intestino do bebê de forma natural e saborosa.',
    image: '33',
    ingredients: ['1/2 maçã', '2 ameixas secas sem caroço', '100ml de água'],
    instructions: [
      'Em uma panela pequena, coloque a ameixa e a água. Deixe ferver por 5 minutos para hidratar e amolecer a ameixa.',
      'Adicione a maçã picada (sem casca) e cozinhe em fogo baixo por mais 10 minutos, ou até a maçã ficar bem macia.',
      'Se sobrar muita água, escorra um pouco.',
      'Amasse tudo com um garfo, formando uma compota rústica.',
      'Sirva morna ou fria.',
    ],
    mealType: 'Sobremesa',
    ageGroup: '6-8 meses',
    texture: 'Amassado',
    cookingTime: '15 min',
    cookingInfo: 'Fogo baixo, panela pequena.',
  },
  {
    id: '34',
    name: 'Biscoitinho de Polvilho (Caseiro)',
    description: 'Um snack que derrete na boca, seguro para o bebê explorar texturas. Uma alternativa saudável aos biscoitos industrializados.',
    image: '34',
    ingredients: ['1 xícara de polvilho doce', '1/4 xícara de azeite de oliva', '1/4 xícara de água morna'],
    instructions: [
        'Pré-aqueça o forno a 160°C.',
        'Em uma tigela, misture o polvilho e o azeite. A mistura vai parecer uma areia úmida.',
        'Aos poucos, adicione a água morna, misturando com as mãos até formar uma massa que não grude.',
        'Faça rolinhos finos ou argolas com a massa e coloque em uma assadeira (não precisa untar).',
        'Asse por cerca de 20-25 minutos, ou até ficarem secos e crocantes, mas sem dourar. Eles devem ficar branquinhos.',
    ],
    mealType: 'Sobremesa',
    ageGroup: '9-11 meses',
    texture: 'Pedaços macios',
    cookingTime: '30 min',
    cookingInfo: 'Forno a 160°C, assadeira.',
  },
  {
      id: '35',
      name: 'Salada de Frutas para Bebês',
      description: 'Uma tigela colorida e cheia de vitaminas, perfeita para o bebê explorar diferentes cores, sabores e texturas com as mãos.',
      image: '35',
      ingredients: ['Pedaços pequenos de manga', 'Uvas sem sementes cortadas em 4 no comprimento', 'Pedaços pequenos de kiwi', 'Mirtilos amassados levemente'],
      instructions: [
          'Lave e pique todas as frutas em pedaços bem pequenos e seguros para a idade do bebê.',
          'Lembre-se de cortar uvas e outras frutas redondas sempre no sentido do comprimento para evitar engasgos.',
          'Misture todas as frutas em uma tigela pequena.',
          'Sirva para o bebê comer com as mãos ou com um garfinho apropriado.',
      ],
      mealType: 'Sobremesa',
      ageGroup: '12+ meses',
      texture: 'Pedaços macios',
      cookingTime: '5 min',
      cookingInfo: 'Sem cozimento.',
  },
  {
      id: '36',
      name: 'Mousse Falso de Chocolate (Abacate e Cacau)',
      description: 'Uma sobremesa surpreendente, saudável e que parece "de adulto". O abacate cria uma base cremosa e o cacau dá o sabor de chocolate, sem nenhum açúcar.',
      image: '36',
      ingredients: ['1/2 abacate bem maduro', '1 colher de chá de cacau em pó 100% (sem açúcar)', '1 tâmara sem caroço (opcional, para adoçar)'],
      instructions: [
          'Se for usar a tâmara, deixe-a de molho em água quente por 10 minutos para amolecer bem. Escorra a água.',
          'Coloque o abacate, o cacau e a tâmara (se usar) em um processador de alimentos ou liquidificador potente.',
          'Bata em alta velocidade até obter um creme completamente liso e homogêneo. Pode ser necessário parar e raspar as laterais.',
          'Leve à geladeira por 30 minutos para firmar um pouco e sirva gelado.',
      ],
      mealType: 'Sobremesa',
      ageGroup: '12+ meses',
      texture: 'Creme',
      cookingTime: '5 min (+ tempo de geladeira)',
      cookingInfo: 'Processador ou liquidificador.',
  },
  {
    id: '37',
    name: 'Purê de Ervilha e Hortelã',
    description: 'Uma combinação surpreendentemente refrescante e nutritiva. A hortelã dá um toque especial ao purê de ervilha.',
    image: '37',
    ingredients: ['1/2 xícara de ervilhas frescas ou congeladas', '2-3 folhas de hortelã fresca', '1 fio de azeite'],
    instructions: [
      'Cozinhe as ervilhas no vapor ou em pouca água fervente por cerca de 5-7 minutos, até ficarem bem macias.',
      'Escorra as ervilhas e coloque-as em um processador ou liquidificador junto com as folhas de hortelã.',
      'Bata até obter um purê liso. Se necessário, adicione uma colher de sopa de água para ajudar a bater.',
      'Regue com um fio de azeite antes de servir morno ou frio.',
    ],
    mealType: 'Almoço',
    ageGroup: '6-8 meses',
    texture: 'Purê',
    cookingTime: '10 min',
    cookingInfo: 'Fogo médio, panela a vapor ou comum.',
  },
  {
    id: '38',
    name: 'Tomate e Pepino em Palitos (BLW)',
    description: 'Um lanche ou entrada fresca e ótima para o bebê explorar com as mãos, especialmente no calor ou para aliviar gengivas doloridas.',
    image: '38',
    ingredients: ['1/4 de tomate maduro, mas firme', 'Um pedaço de pepino japonês'],
    instructions: [
      'Lave bem o tomate. Corte em 4 partes e retire as sementes. Ofereça o "pétala" do tomate para o bebê.',
      'Lave e descasque o pepino. Corte em tiras longas e grossas, no formato de um dedo de adulto, para que o bebê possa segurar firmemente.',
      'Sirva os palitos de legumes frios.',
      'Supervisione sempre, garantindo que o bebê não morda pedaços grandes demais.',
    ],
    mealType: 'Almoço',
    ageGroup: '9-11 meses',
    texture: 'Pedaços macios',
    cookingTime: '3 min',
    cookingInfo: 'Sem cozimento.',
  },
  {
    id: '39',
    name: 'Mini Pizza de Abobrinha',
    description: 'Uma versão divertida, sem massa e muito saudável da pizza. As rodelas de abobrinha servem como base.',
    image: '39',
    ingredients: ['4 rodelas grossas de abobrinha (aprox. 1cm)', '2 colheres de sopa de molho de tomate caseiro', 'Queijo muçarela ou parmesão ralado (opcional)', 'Orégano para polvilhar'],
    instructions: [
      'Pré-aqueça o forno a 200°C.',
      'Disponha as rodelas de abobrinha em uma assadeira.',
      'Espalhe uma pequena quantidade de molho de tomate sobre cada rodela.',
      'Se for usar, polvilhe o queijo e o orégano por cima.',
      'Leve ao forno por cerca de 10-15 minutos, ou até a abobrinha amolecer e o queijo derreter.',
      'Deixe amornar antes de servir.',
    ],
    mealType: 'Jantar',
    ageGroup: '12+ meses',
    texture: 'Pedaços macios',
    cookingTime: '15 min',
    cookingInfo: 'Forno a 200°C, assadeira.',
  },
  {
    id: '40',
    name: 'Sorbet de Morango e Banana',
    description: 'Um "sorvete" cremoso, gelado, saudável e feito com apenas 2 ingredientes. A banana congelada cria a base perfeita.',
    image: '40',
    ingredients: ['1 xícara de morangos congelados', '1 banana madura, congelada em rodelas'],
    instructions: [
      'Certifique-se de que as frutas estão bem congeladas (pelo menos 4 horas no freezer).',
      'Coloque os morangos e as rodelas de banana em um processador de alimentos potente.',
      'Bata, parando para raspar as laterais, até que as frutas se quebrem e comecem a formar um creme homogêneo e liso. Isso pode levar alguns minutos.',
      'Sirva imediatamente, pois derrete rápido!',
    ],
    mealType: 'Sobremesa',
    ageGroup: '12+ meses',
    texture: 'Creme',
    cookingTime: '5 min',
    cookingInfo: 'Processador de alimentos.',
  },
  {
    id: '41',
    name: 'Mingau de Milho Verde (Cremoso)',
    description: 'Um clássico brasileiro adaptado, aproveitando o sabor naturalmente doce do milho. Muito cremoso e reconfortante.',
    image: '41',
    ingredients: ['Grãos de 1 espiga de milho verde', '1 xícara de leite (materno, fórmula ou vegetal)', '1 pitada de canela (opcional)'],
    instructions: [
      'Bata os grãos de milho com o leite no liquidificador por cerca de 2 minutos.',
      'Passe a mistura por uma peneira fina, apertando bem para extrair todo o líquido.',
      'Leve esse creme de milho a uma panela em fogo baixo.',
      'Cozinhe, mexendo sempre, por cerca de 5-8 minutos, até engrossar e cozinhar bem.',
      'Sirva morno, com canela polvilhada por cima se desejar.',
    ],
    mealType: 'Café da Manhã',
    ageGroup: '9-11 meses',
    texture: 'Creme',
    cookingTime: '15 min',
    cookingInfo: 'Fogo baixo, liquidificador e panela.',
  },
  {
    id: '42',
    name: 'Sopa Creme de Beterraba',
    description: 'Uma sopa de cor vibrante, sabor terroso e levemente adocicado. Rica em nutrientes e uma forma diferente de oferecer beterraba.',
    image: '42',
    ingredients: ['1 beterraba pequena cozida e descascada', '1/2 batata pequena cozida', '1 fio de azeite', 'Água do cozimento'],
    instructions: [
      'Certifique-se de que a beterraba e a batata estão bem cozidas e macias.',
      'No liquidificador, coloque os legumes cozidos e um pouco da água em que foram cozidos (comece com 1/2 xícara).',
      'Bata em alta velocidade até obter um creme liso e aveludado.',
      'Aqueça levemente em uma panela antes de servir, adicionando o fio de azeite.',
      'Cuidado, beterraba mancha tudo!',
    ],
    mealType: 'Jantar',
    ageGroup: '6-8 meses',
    texture: 'Sopa',
    cookingTime: '5 min (com legumes já cozidos)',
    cookingInfo: 'Liquidificador e panela.',
  },
  {
    id: '43',
    name: 'Tirinhas de Frango Grelhado com Ervas',
    description: 'Proteína em um formato fácil de pegar e ideal para treinar a mastigação. As ervas adicionam um aroma delicioso.',
    image: '43',
    ingredients: ['50g de filé de frango', 'Gotas de limão', 'Ervas finas secas (orégano, tomilho) a gosto', 'Azeite para grelhar'],
    instructions: [
      'Corte o filé de frango em tiras grossas.',
      'Tempere as tiras com as gotas de limão e as ervas.',
      'Aqueça uma frigideira antiaderente ou grill com um fio de azeite em fogo médio.',
      'Grelhe as tiras de frango por cerca de 3-4 minutos de cada lado, até que estejam cozidas por dentro e douradas por fora.',
      'Deixe amornar e sirva para o bebê pegar com a mão.',
    ],
    mealType: 'Almoço',
    ageGroup: '12+ meses',
    texture: 'Pedaços macios',
    cookingTime: '10 min',
    cookingInfo: 'Fogo médio, frigideira ou grill.',
  },
  {
    id: '44',
    name: 'Iogurte Natural com Frutas Vermelhas',
    description: 'Simples, rápido e delicioso. Uma combinação de probióticos do iogurte com antioxidantes das frutas vermelhas.',
    image: '44',
    ingredients: ['1/2 pote de iogurte natural integral (sem açúcar)', '3 morangos picados ou 5 mirtilos amassados'],
    instructions: [
      'Em uma tigela, coloque o iogurte.',
      'Adicione as frutas vermelhas (morangos picados em pedaços seguros ou mirtilos levemente amassados com um garfo).',
      'Misture delicadamente.',
      'Sirva frio. Introduza laticínios conforme orientação pediátrica.',
    ],
    mealType: 'Café da Manhã',
    ageGroup: '9-11 meses',
    texture: 'Creme',
    cookingTime: '3 min',
    cookingInfo: 'Sem cozimento.',
  },
  {
    id: '45',
    name: 'Purê de Abóbora com Carne Seca',
    description: 'Uma combinação de sabores do Brasil. O doce da abóbora contrasta com o salgadinho da carne seca, criando um prato surpreendente.',
    image: '45',
    ingredients: ['1 xícara de abóbora cozida e amassada', '2 colheres de sopa de carne seca dessalgada, cozida e bem desfiada', '1 fio de azeite', 'Cebolinha picada para finalizar'],
    instructions: [
      'Certifique-se de que a carne seca foi muito bem dessalgada (deixada de molho em água trocada várias vezes) e cozida na pressão até ficar macia.',
      'Em uma panela, aqueça o azeite e refogue rapidamente a carne seca desfiada para aquecer.',
      'Misture a carne refogada com o purê de abóbora.',
      'Sirva morno, polvilhado com cebolinha fresca.',
    ],
    mealType: 'Almoço',
    ageGroup: '12+ meses',
    texture: 'Amassado',
    cookingTime: '10 min (com ingredientes pré-preparados)',
    cookingInfo: 'Fogo baixo, panela pequena.',
  },
  {
    id: '46',
    name: 'Creme de Milho Verde Caseiro',
    description: 'Esqueça a versão em lata! Este creme é feito com milho fresco e tem uma doçura natural incomparável. Uma delícia aveludada.',
    image: '46',
    ingredients: ['1 espiga de milho verde', '1/2 xícara de leite ou água', '1/4 de cebola pequena (opcional)', '1 fio de azeite'],
    instructions: [
      'Com uma faca, retire os grãos de milho da espiga.',
      'Bata os grãos no liquidificador com o leite/água até ficar homogêneo.',
      'Passe a mistura por uma peneira fina para remover as casquinhas.',
      'Em uma panela, refogue a cebola picadinha no azeite (se usar). Despeje o creme de milho e cozinhe em fogo baixo, mexendo sempre, até engrossar (cerca de 8 minutos).',
    ],
    mealType: 'Jantar',
    ageGroup: '9-11 meses',
    texture: 'Creme',
    cookingTime: '15 min',
    cookingInfo: 'Fogo baixo, panela média.',
  },
  {
    id: '47',
    name: 'Palitos de Cenoura Assada com Alecrim',
    description: 'Assar a cenoura realça sua doçura natural. Em formato de palito, é um "snack" saudável e perfeito para o bebê treinar a mastigação.',
    image: '47',
    ingredients: ['1 cenoura média', 'Azeite de oliva', '1 raminho de alecrim fresco (ou uma pitada do seco)'],
    instructions: [
      'Pré-aqueça o forno a 200°C.',
      'Descasque a cenoura e corte-a em palitos grossos.',
      'Em uma tigela, misture os palitos de cenoura com um fio de azeite e as folhas de alecrim.',
      'Espalhe em uma assadeira em uma única camada.',
      'Asse por 20-25 minutos, ou até que estejam macios por dentro e levemente dourados por fora.',
      'Deixe amornar antes de servir.',
    ],
    mealType: 'Almoço',
    ageGroup: '9-11 meses',
    texture: 'Pedaços macios',
    cookingTime: '25 min',
    cookingInfo: 'Forno a 200°C, assadeira.',
  },
  {
    id: '48',
    name: 'Geleia de Morango com Chia (Sem Açúcar)',
    description: 'Uma geleia 100% natural, adoçada apenas com o doce da fruta. A chia ajuda a dar a consistência e adiciona fibras e ômega 3.',
    image: '48',
    ingredients: ['1 xícara de morangos frescos picados', '1 colher de sopa de sementes de chia'],
    instructions: [
      'Leve os morangos a uma panela em fogo baixo.',
      'Cozinhe, mexendo e amassando os pedaços com uma colher, por cerca de 10 minutos, até os morangos desmancharem e formarem uma calda.',
      'Desligue o fogo, adicione as sementes de chia e misture bem.',
      'Deixe descansar por 10 minutos. A chia vai inchar e engrossar a geleia.',
      'Guarde em um pote de vidro na geladeira. Sirva com frutas, iogurte ou pães.',
    ],
    mealType: 'Café da Manhã',
    ageGroup: '12+ meses',
    texture: 'Creme',
    cookingTime: '15 min',
    cookingInfo: 'Fogo baixo, panela pequena.',
  },
  {
    id: '49',
    name: 'Cuscuz Nordestino com Ovo',
    description: 'Um café da manhã ou jantar típico, forte e nutritivo. O cuscuz é versátil e combina perfeitamente com a cremosidade do ovo.',
    image: '49',
    ingredients: ['2 colheres de sopa de flocão de milho', '4 colheres de sopa de água', '1 ovo cozido', '1 fio de azeite'],
    instructions: [
      'Em uma tigela, hidrate o flocão de milho com a água. Deixe descansar por 5 minutos.',
      'Cozinhe o cuscuz no vapor em uma cuscuzeira por cerca de 10 minutos, ou no micro-ondas por 1 minuto.',
      'Enquanto isso, cozinhe o ovo e amasse-o com um garfo.',
      'Desenforme o cuscuz, regue com azeite e misture o ovo amassado.',
      'Sirva morno.',
    ],
    mealType: 'Café da Manhã',
    ageGroup: '12+ meses',
    texture: 'Amassado',
    cookingTime: '15 min',
    cookingInfo: 'Fogo médio, cuscuzeira ou micro-ondas.',
  },
  {
    id: '50',
    name: 'Compota de Pêssego com Anis',
    description: 'Uma sobremesa delicada, perfumada e saborosa. O anis estrelado adiciona um aroma especial que encanta o paladar.',
    image: '50',
    ingredients: ['1 pêssego maduro e firme', '1 anis estrelado (opcional)', '100ml de água'],
    instructions: [
      'Lave, descasque e corte o pêssego em fatias, removendo o caroço.',
      'Em uma panela pequena, coloque as fatias de pêssego, a água e o anis estrelado (se for usar).',
      'Cozinhe em fogo baixo por cerca de 10-15 minutos, até o pêssego ficar bem macio e a calda levemente encorpada.',
      'Retire e descarte o anis estrelado.',
      'Amasse o pêssego com um garfo ou sirva em pedaços, dependendo da idade do bebê.',
      'Sirva morno ou frio.',
    ],
    mealType: 'Sobremesa',
    ageGroup: '9-11 meses',
    texture: 'Amassado',
    cookingTime: '15 min',
    cookingInfo: 'Fogo baixo, panela pequena.',
  }
];

export const foodHistory: FoodHistory[] = [
  { id: '1', foodName: 'Banana', date: '2024-07-20', reaction: 'liked' },
  { id: '2', foodName: 'Mamão', date: '2024-07-20', reaction: 'liked' },
  { id: '3', foodName: 'Abacate', date: '2024-07-19', reaction: 'disliked' },
  { id: '4', foodName: 'Batata doce', date: '2024-07-18', reaction: 'liked' },
  { id: '5', foodName: 'Cenoura', date: '2024-07-17', reaction: 'strange' },
  { id: '6', foodName: 'Chuchu', date: '2024-07-16', reaction: 'none' },
];

export const guideTopics: GuideTopic[] = [
  {
    id: '1',
    title: 'Quando começar a introdução alimentar?',
    content: 'A recomendação geral é iniciar por volta dos 6 meses. O bebê deve mostrar sinais de prontidão, como sentar com o mínimo de apoio, ter bom controle da cabeça e mostrar interesse pela comida dos adultos.',
  },
  {
    id: '2',
    title: 'Texturas recomendadas por fase',
    content: 'Comece com purês lisos e evolua gradualmente. Aos 6-7 meses, purês e papas. Aos 8-9 meses, alimentos amassados com garfo. A partir de 10-12 meses, alimentos em pedaços pequenos e macios para o bebê pegar com as mãos.',
  },
  {
    id: '3',
    title: 'Dicas de líquidos para a introdução',
    content: 'Até os 6 meses, o leite materno ou a fórmula são suficientes. Após o início da introdução alimentar, ofereça água filtrada e fervida (depois resfriada) nos intervalos das refeições. Use um copinho de treinamento. Sucos não são recomendados antes de 1 ano.',
  },
  {
    id: '4',
    title: 'Engasgo vs. Reflexo de GAG',
    content: 'O reflexo de GAG é um movimento natural que o bebê faz para evitar o engasgo, empurrando a comida para fora com a língua. Parece que ele está tossindo, mas não há obstrução. Já o engasgo real é silencioso, o bebê não consegue respirar e a pele pode mudar de cor. Mantenha a calma, aprenda manobras de desengasgo e nunca deixe o bebê sozinho enquanto come.',
  },
  {
    id: '5',
    title: 'Cuidados Básicos',
    content: 'Ofereça um alimento novo de cada vez e espere 2-3 dias para observar possíveis reações. Nunca adicione sal, açúcar ou mel. Esteja sempre presente e supervisionando a alimentação para evitar engasgos.',
  },
];
